"use client";

import { useState, useEffect } from "react";
import { getCurrentUser, type UserProfile } from "@/lib/banking";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { BrainCircuit, Sparkles, TrendingDown, ShieldCheck, ArrowRight, Lightbulb } from "lucide-react";
import { getPersonalFinancialAdvice, type GetPersonalFinancialAdviceOutput } from "@/ai/flows/personal-financial-advisor";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";

export default function AdvisorPage() {
  const [user, setUser] = useState<UserProfile | null>(null);
  const [loading, setLoading] = useState(false);
  const [advice, setAdvice] = useState<GetPersonalFinancialAdviceOutput | null>(null);

  useEffect(() => {
    setUser(getCurrentUser());
  }, []);

  const fetchAdvice = async () => {
    if (!user) return;
    setLoading(true);
    try {
      // Map transactions to the format required by the AI flow
      const mappedHistory = user.transactions.map(t => ({
        date: t.date,
        description: t.description,
        amount: t.type === 'incoming' ? t.amount : -t.amount,
        category: t.category
      }));

      const result = await getPersonalFinancialAdvice({
        transactionHistory: mappedHistory,
        currentBalance: user.balance,
        financialGoals: "Save more for an emergency fund and optimize daily spending."
      });
      setAdvice(result);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  if (!user) return null;

  return (
    <div className="max-w-5xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-2 duration-500">
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div>
          <h1 className="text-3xl font-headline font-bold flex items-center gap-3">
            <BrainCircuit className="text-accent h-8 w-8" /> Apex AI Advisor
          </h1>
          <p className="text-muted-foreground mt-2">Personalized financial strategy generated by our advanced reasoning engine.</p>
        </div>
        {!advice && !loading && (
          <Button size="lg" className="rounded-full px-8 gap-2 shadow-lg shadow-accent/20" onClick={fetchAdvice}>
            <Sparkles size={18} /> Analyze My Finances
          </Button>
        )}
      </div>

      {!advice && !loading && (
        <Card className="border-dashed border-2 bg-muted/20">
          <CardContent className="flex flex-col items-center justify-center py-20 text-center">
            <div className="w-16 h-16 rounded-full bg-accent/10 flex items-center justify-center text-accent mb-6">
              <BrainCircuit size={32} />
            </div>
            <h3 className="text-xl font-bold mb-2">Ready to optimize?</h3>
            <p className="text-muted-foreground max-w-sm">Our AI will scan your transaction history to provide custom budgeting and savings strategies.</p>
          </CardContent>
        </Card>
      )}

      {loading && (
        <div className="space-y-6">
          <Skeleton className="h-[200px] w-full rounded-xl" />
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Skeleton className="h-[300px] rounded-xl" />
            <Skeleton className="h-[300px] rounded-xl" />
          </div>
        </div>
      )}

      {advice && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <Card className="md:col-span-3 border-none bg-accent text-white overflow-hidden shadow-2xl">
            <div className="p-8 relative">
              <CardTitle className="text-2xl mb-4 flex items-center gap-2">
                <ShieldCheck /> Executive Summary
              </CardTitle>
              <p className="text-xl leading-relaxed opacity-90 max-w-4xl">
                {advice.summary}
              </p>
              <div className="absolute right-[-20px] top-[-20px] opacity-10">
                <Sparkles size={150} />
              </div>
            </div>
          </Card>

          <Card className="border-border shadow-sm">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-accent">
                <TrendingDown size={20} /> Budgeting Tips
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {advice.budgetingTips.map((tip, i) => (
                <div key={i} className="flex gap-3 p-3 bg-muted/30 rounded-lg hover:bg-muted/50 transition-colors">
                  <div className="mt-1 h-5 w-5 rounded-full bg-accent/10 flex-shrink-0 flex items-center justify-center text-[10px] font-bold text-accent">
                    {i+1}
                  </div>
                  <p className="text-sm leading-snug">{tip}</p>
                </div>
              ))}
            </CardContent>
          </Card>

          <Card className="border-border shadow-sm">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-accent">
                <Lightbulb size={20} /> Savings Strategies
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {advice.savingsStrategies.map((strategy, i) => (
                <div key={i} className="flex gap-3 p-3 bg-muted/30 rounded-lg hover:bg-muted/50 transition-colors">
                  <div className="mt-1 h-5 w-5 rounded-full bg-accent/10 flex-shrink-0 flex items-center justify-center text-[10px] font-bold text-accent">
                    {i+1}
                  </div>
                  <p className="text-sm leading-snug">{strategy}</p>
                </div>
              ))}
            </CardContent>
          </Card>

          <Card className="border-border shadow-sm">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-accent">
                <ArrowRight size={20} /> Actionable Steps
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {advice.actionableSteps.map((step, i) => (
                <div key={i} className="group cursor-pointer flex gap-3 p-3 border border-transparent hover:border-accent/20 rounded-lg transition-all">
                   <Badge variant="secondary" className="h-fit py-0 px-2 mt-0.5">{i+1}</Badge>
                   <p className="text-sm font-medium group-hover:text-accent">{step}</p>
                </div>
              ))}
            </CardContent>
          </Card>

          <div className="md:col-span-3 flex justify-center">
            <Button variant="ghost" className="text-muted-foreground" onClick={() => setAdvice(null)}>
              Reset Analysis
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}